version: '3'
services:
  first-app:
    build:
      args:
        JAR_FILE: ./runnable-all/first-app/target/first-app-1.0-SNAPSHOT.jar
      context: .
      dockerfile: ./runnable-all/first-app/Dockerfile
    container_name: first-app
    image: lagoshny/ubuntu-oracle-java-8
    ports:
    - 8081:8080
  second-app:
    build:
      args:
        JAR_FILE: ./runnable-all/second-app/target/second-app-1.0-SNAPSHOT.jar
      context: .
      dockerfile: ./runnable-all/second-app/Dockerfile
    container_name: second-app
    image: lagoshny/ubuntu-oracle-java-8
    ports:
    - 8082:8080