services:
  app:
    build:
      args:
        JAR_FILE: ./target/spring-docker-1.0-SNAPSHOT.jar
      context: .
    container_name: app
    entrypoint:
    - java
    - -Djava.security.egd=file:/dev/./urandom
    - -jar
    - project/spring-docker-1.0-SNAPSHOT.jar
    image: lagoshny/ubuntu-oracle-java-8
    ports:
    - 8080:8080
    volumes:
    - ./target:/project
version: '3'
