services:
  first-app:
    build:
      args:
        JAR_FILE: /home/ilya/Projects/springdocker/runnable-all/first-app/target/first-app-1.0-SNAPSHOT.jar
      context: .
    container_name: first-app
    entrypoint:
    - java
    - -Djava.security.egd=file:/dev/./urandom
    - -jar
    - project/first-app-1.0-SNAPSHOT.jar
    image: lagoshny/ubuntu-oracle-java-8
    ports:
    - 8081:8080
    volumes:
    - /home/ilya/Projects/springdocker/runnable-all/first-app/target:/project
  second-app:
    build:
      args:
        JAR_FILE: /home/ilya/Projects/springdocker/runnable-all/second-app/target/second-app-1.0-SNAPSHOT.jar
      context: .
    container_name: second-app
    entrypoint:
    - java
    - -Djava.security.egd=file:/dev/./urandom
    - -jar
    - project/second-app-1.0-SNAPSHOT.jar
    image: lagoshny/ubuntu-oracle-java-8
    ports:
    - 8082:8080
    volumes:
    - /home/ilya/Projects/springdocker/runnable-all/second-app/target:/project
version: '3'
